cc_binary(
    name = "2a",
    srcs = ["2a.cc"],
    deps = [
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/strings",
    ],
)

cc_binary(
    name = "2b",
    srcs = ["2b.cc"],
    deps = [
        "@com_google_absl//absl/container:flat_hash_set",
    ],
)
