cc_binary(
    name = "3a",
    srcs = ["3a.cc"],
    deps = [
        "@com_google_absl//absl/container:flat_hash_set",
        "@com_google_absl//absl/strings",
    ],
)

cc_binary(
    name = "3b",
    srcs = ["3b.cc"],
    deps = [
        "@com_google_absl//absl/container:flat_hash_set",
    ],
)
